title: Adam Guerra
logo: "/assets/img/profilepic.JPG"
description: >
  Data Analyst | Environmental Scientist
  <br><br>
  <a href="https://www.linkedin.com/in/adamguerra01/">LinkedIn Profile</a>
  <br><br>
  <a href="Resume.pdf"> Resume Download<a/>
  <br><br>
  <a href="Water Data Project HTMLs"> Water Data Project Download</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
