title: Adam Guerra
logo: "/assets/img/profilepic.jpg"
description: >
Data Analyst | Environmental Scientist
<br><br>
<a href="https://www.linkedin.com/in/adamguerra01/">LinkedIn Profile</a>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
