title: Adam Guerra
logo: "/assets/img/profilepic.JPG"
description: >
  Data Analyst | Environmental Scientist
  <br><br>
  <a href="https://www.linkedin.com/in/adamguerra01/">LinkedIn Profile</a>
  <br><br>
  [Resume Download](/Resume.pdf)
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
