title: Adam Guerra
logo: "/assets/img/profilepic.JPG"
description: >
  Data Analyst | Environmental Scientist
  <br><br>
  <a href="https://www.linkedin.com/in/adamguerra01/">LinkedIn Profile</a>
  <br><br>
  <a href="Resume.pdf"> Resume Download<a/>
  <br><br>
  <p>Email: AdamGuerra01@gmail.com</p>
  <br><br>
  <small>Copies of HTML of code available upon request.</small>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
